version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /Users/monkey/Documents/Docker-compose/docker-data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duytc
    ports:
      - '5432:5432'

