version: '3.9'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - /Users/duytc/Documents/Docker/Docker-data/minio:/data
    environment:
      MINIO_ROOT_USER: duytc
      MINIO_ROOT_PASSWORD: DUYTC1122
    command: server --console-address ":9001" /data
    hostname: my.domain 
    ports:
      - '9000:9000'
      - '9001:9001'
volumes:
  minio:
